/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f401xc_gpio_driver.h"
#include "stm32f401xc_EXTI_driver.h"
#include "SevenSegment_driver.h"

#define DELAY_MS(d)		do{unsigned int i = d*4000;while(i--){asm("NOP");} }while(0)

void Clock_Init(void) {
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_SYSCFG_CLK_EN();
}

void Interrupt(void){
	GPIO_PinConfig_t PinConfig;
	PinConfig.GPIO_PinNumber = GPIO_PIN_0;
	PinConfig.GPIO_MODE = GPIO_MODE_OP;
	PinConfig.GPIO_TYPE = GPIO_TYPE_PP;
	PinConfig.GPIO_PU_PD = GPIO__PU_PD_NONE;
	PinConfig.GPIO_Output_Speed = GPIO_SPEED_LOW;
	MCAL_GPIO_Init(GPIOA, &PinConfig);
	MCAL_GPIO_TogglePin(GPIOA, GPIO_PIN_0);
}

void GPIO_Init(void) {
	EXTI_PinConfig_t EXTI_PB7;

	EXTI_PB7.EXTI_PIN = EXTI7_PB7;
	EXTI_PB7.EXTI_Enable = EXTI_IRQ_EN;
	EXTI_PB7.EXTI_EdgeSelect = EXTI_TRIGGER_RISING;
	EXTI_PB7.P_IRQ_CallBack = Interrupt;
	MCAL_EXTI_GPIO_Init(&EXTI_PB7);
}



int main(void) {
	Clock_Init();
	GPIO_Init();

	while (1);
}
