/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f401xc_EXTI_driver.h"
#include "Led_Matrix_driver.h"
#include "SevenSegment_driver.h"
#include "DAC_driver.h"
#include "Serial2Parallel_drivers.h"
#include "IR_driver.h"
#include "stm32f401xc_USART_driver.h"
#include "stm32f401xc_SPI_driver.h"
#include "stm32f401xc_Timer_driver.h"


void Clock_Init(void){
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_SYSCFG_CLK_EN();
}

int main(void){
    Clock_Init();

    GPIO_PinConfig_t pinCfg;
    pinCfg.GPIO_PinNumber = GPIO_PIN_6;
    pinCfg.GPIO_MODE = GPIO_MODE_AF;
    pinCfg.GPIO_Output_Speed = GPIO_SPEED_HIGH;
    pinCfg.GPIO_TYPE = GPIO_TYPE_PP;
    pinCfg.GPIO_PU_PD = GPIO_PU_PD_NONE;
    pinCfg.GPIO_AFx = GPIO_AF2;
    MCAL_GPIO_Init(GPIOA, &pinCfg);

    Timer_Config_t cfg;
    Timer_OutputCompare_Config_t ocCfg;

    cfg.BaseConfig.TIMERx = TIMER3;
    cfg.OCConfig = &ocCfg;
    cfg.OCConfig->TIMER_Channel   = TIMER_Channel_1;
    cfg.OCConfig->TIMER_Frequency = 1000;

    MCAL_Timer_PWM_Init(&cfg, 0);

    while(1){
        for(int duty = 0; duty <= 100; duty++){
        	MCAL_Timer_PWM_SetDuty(&cfg, duty);
            for(volatile int d=0; d<2000; d++);
        }
        for(int duty = 100; duty >= 0; duty--){
        	MCAL_Timer_PWM_SetDuty(&cfg, duty);
            for(volatile int d=0; d<2000; d++);
        }
    }
}
