/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f401xc_SysTick_driver.h"
#include "stm32f401xc_gpio_driver.h"
#include "stm32f401xc_EXTI_driver.h"
#include "Led_Matrix_driver.h"
#include "SevenSegment_driver.h"
#include "DAC_driver.h"
#include "sound.h"

void Clock_Init(void) {
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_SYSCFG_CLK_EN();
}

void GPIO_Init(void){
	GPIO_PinConfig_t sound_pins[8] = {
			{.GPIO_PinNumber = GPIO_PIN_0, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
			{.GPIO_PinNumber = GPIO_PIN_1, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
			{.GPIO_PinNumber = GPIO_PIN_2, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
			{.GPIO_PinNumber = GPIO_PIN_3, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
			{.GPIO_PinNumber = GPIO_PIN_4, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
			{.GPIO_PinNumber = GPIO_PIN_5, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
			{.GPIO_PinNumber = GPIO_PIN_6, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
			{.GPIO_PinNumber = GPIO_PIN_7, .GPIO_MODE = GPIO_MODE_OP, .GPIO_TYPE = GPIO_TYPE_PP, .GPIO_Output_Speed = GPIO_SPEED_LOW, .GPIO_PU_PD = GPIO__PU_PD_NONE},
	};

	HAL_DAC_Init(GPIOA, sound_pins, 8);
}

void EXTI_DAC_Handler(void){
	MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_7);

	static uint32_t iterator = 0;

	HAL_DAC_SendAudioSample(test_raw, iterator);

	if (iterator < test_raw_len){
		iterator++;
	}
	else{
		iterator = 0;
	}
}

void EXTI_GPIOInit(void){
	EXTI_PinConfig_t EXTI_PinConf;

	EXTI_PinConf.EXTI_PIN = EXTI6_PB6;
	EXTI_PinConf.EXTI_Enable = EXTI_IRQ_EN;
	EXTI_PinConf.EXTI_EdgeSelect = EXTI_TRIGGER_RISING;
	EXTI_PinConf.P_IRQ_CallBack = EXTI_DAC_Handler;
	MCAL_EXTI_GPIO_Init(&EXTI_PinConf);
}

void TestLed_Init(void){
	GPIO_PinConfig_t test_led;

	test_led.GPIO_PinNumber = GPIO_PIN_7;
	test_led.GPIO_MODE = GPIO_MODE_OP;
	test_led.GPIO_TYPE = GPIO_TYPE_PP;
	test_led.GPIO_Output_Speed = GPIO_SPEED_LOW;
	test_led.GPIO_PU_PD = GPIO__PU_PD_NONE;

	MCAL_GPIO_Init(GPIOB, &test_led);
}

int main(void){
	// Select AHB / 8 temporary until i make driver or it
	RCC->CR |= (1 << 16);
	while (!(RCC->CR & (1 << 17)));
	RCC->CFGR &= ~(0x3 << 0);
	RCC->CFGR |= (0x1 << 0);
	while (((RCC->CFGR >> 2) & 0x3) != 0x1);

	Clock_Init();
	GPIO_Init();
	EXTI_GPIOInit();
	TestLed_Init();

	while(1);

	return 0 ;
}

